version: "3.3"
services: 
   db:
      image: mysql:5.6
      environment:
         MYSQL_ROOT_PASSWORD: ${root_password:-Wave123}  
      volumes:
               - ${mysql_persistant_volume:-/tmp/mysql/}:/var/lib/mysql
      networks: 
         - wm_app             
      
   webapp:
      image: tomcat:8.5
      environment:
         wm.mysqlCloudHost: db:3306
         wm.mysqlCloudUsername: root
         wm.mysqlCloudPassword: ${root_password:-Wave123}
      volumes:
            - ${webapp_persistant_volume:-/tmp/tomcat-logs}:/usr/local/tomcat/logs
            - ./dist:/usr/local/tomcat/webapps
      networks: 
          - wm_app
      
   nginx:
      build: 
         context: ./nginx/
      ports:
      - "80:80"
      volumes:
            - ${nginx_persistant_volume:-/tmp/nginx-logs}:/var/log/nginx
      networks: 
         - wm_app
networks:
   wm_app:
      driver: bridge
   

