version: '3.3'
services: 
  db:
    image: mysql:5.6
    environment:
     MYSQL_ROOT_PASSWORD: ${root_password:-Wave123}  
    volumes:
            - ${mysql_persistant_volume:-/tmp/mysql/}:/var/lib/mysql
    networks: 
     - app_network                 
    
  webapp:
    build:
        context: ./
        args: 
         profile: ${maven_build:-deployment}
    environment:
      wm.mysqlCloudHost: db:3306
      wm.mysqlCloudUsername: root
      wm.mysqlCloudPassword: ${root_password:-Wave123}
    volumes:
            - ${webapp_persistant_volume:-/tmp/tomcat-logs}:/usr/local/tomcat/logs
    networks: 
     - app_network
   
  nginx:
    build: 
        context: ./nginx/
    ports:
       - "80:80"
    volumes:
            - ${nginx_persistant_volume:-/tmp/nginx-logs}:/var/log/nginx
    networks: 
        - app_network
networks:
   app_network:
      driver: bridge
      




