version: '3.3'
services: 
   app-builder:
      #user: ${wm_user}
      #build/run when flag enabled. 
      image: wavemaker/wm-app-builder:1.0
      volumes: 
         - ./:/usr/local/content/app
         - /etc/group:/etc/group:ro
         - /etc/passwd:/etc/passwd:ro
         - /etc/shadow:/etc/shadow:ro
         - $HOME/.m2:/root/.m2
      networks: 
         - app_network
   db:
      image: mysql:5.6
      environment:
         MYSQL_ROOT_PASSWORD: ${root_password:-Wave123}  
      volumes:
               - ${mysql_persistant_volume:-/tmp/mysql/}:/var/lib/mysql
      networks: 
         - app_network                 
      
   webapp:
      image: tomcat:8.5
      depends_on: 
          - app-builder
      environment:
         wm.mysqlCloudHost: db:3306
         wm.mysqlCloudUsername: root
         wm.mysqlCloudPassword: ${root_password:-Wave123}
      volumes:
            - ${webapp_persistant_volume:-/tmp/tomcat-logs}:/usr/local/tomcat/logs
            - ./dist:/usr/local/tomcat/webapps
      networks: 
          - app_network
      
   nginx:
      build: 
         context: ./nginx/
      ports:
      - "80:80"
      volumes:
            - ${nginx_persistant_volume:-/tmp/nginx-logs}:/var/log/nginx
      networks: 
         - app_network
networks:
   app_network:
      driver: bridge
   

