apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdeploy
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /var/log/nginx
            name: nginxvolume
      volumes:
        - name: nginxvolume
          hostPath:
              path: /home/nginx/logs
              type: DirectoryOrCreate

      
