---
kind: "Secret"
apiVersion: "v1"
metadata:
  labels:
    hyscale.io/service-name: "mysql"
    hyscale.io/environment-name: "dev"
    hyscale.io/app-name: "testabc"
  name: "testabc-mysql"
data:
  MYSQL_ROOT_PASSWORD: "d0B2ZW1Aa2VS"
