---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  labels:
    hyscale.io/service-name: "webapp"
    hyscale.io/environment-name: "dev"
    hyscale.io/app-name: "testabc"
  name: "testabc-webapp"
data:
  wm.mysqlCloudHost: "mysql:3306"
  wm.mysqlCloudUsername: "root"
binaryData: {}
