---
kind: "Secret"
apiVersion: "v1"
metadata:
  labels:
    hyscale.io/service-name: "webapp"
    hyscale.io/environment-name: "dev"
    hyscale.io/app-name: "testabc"
  name: "testabc-webapp"
data:
  wm.mysqlCloudPassword: "d0B2ZW1Aa2VS"
